### ISSUE TITLE
T1 complement alert ingestion

### ISSUE THREAD

**Issue by wombaugh** [AmpelProject/Ampel-alerts#1]
A common request will be to complement object data. This can take different shapes: adding archive detections from the same instruments, searching for detections in other instrument datastreams, reading input from forced photometry at a position etc.

It is currently not clear how to do this correctly and efficiently. Presumably a T1, but it could also be combined with a T0 stage, will run and collect data. In the next tier, T2s need be run, possibly both on the raw and complemented compounds. 

Finally, some selection mechanism at the T3 stage should allow users to easily decide which kind of compounds to use. For example, with the example of combining alert data with archive data, a lot of users would only want to use the T2 output that was based on both alert and archive data _even if nothing new was found in the alert search_.

**Comment by vbrinnel** [comment]
Should be solved in `v0.8`.
Objections to closing this issue ?

**Comment by vbrinnel** [comment]
Please feel free to reopen if need be
