### ISSUE TITLE
Consistent datapoint selection for T2s

### ISSUE THREAD

**Issue by wombaugh** [AmpelProject/Ampel-alerts#17]
The current (v07) setup with alert and archive states make it impossible to use Point T2s in the same way for alert and archive analaysis. For the first kind, one would like to run based on the 'first' datapoint (to avoid reruns). However, an archive run will add earlier objects creating a difference between T2 ticket link and database content. An archive (offline) analysis instead has to use the 'last' datapoint.

This question is directly related to how to handle alert content, auto/retro complete and archive states. For v08 it would be great with a consistent, stable solution.

**Comment by vbrinnel** [comment]
_For v08 it would be great with a consistent, stable solution._
Already the case
